# Generated by Django 4.0.1 on 2022-01-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
    ]
